### ISSUE TITLE
ayuda 

### ISSUE THREAD

**Issue by abelnexus** [giansalex/facturacionTIS#6]
CS0006	No se encontró el archivo de metadatos 'C:\Users\GRAFIKAS\Desktop\facturacionTIS-version_1\FacturacionElectronica.GeneradorXml\bin\Debug\FacturacionElectronica.GeneradorXml.dll'	
CS0006	No se encontró el archivo de metadatos 'C:\Users\GRAFIKAS\Desktop\facturacionTIS-version_1\FacturacionElectronica.Homologacion\bin\Debug\FacturacionElectronica.Homologacion.dll'

**Comment by abelnexus** [comment]
no encuentro las librerias no deja compilar tambien vota error con el certificado
No se puede importar el archivo de clave siguiente: FacturacionTIS.pfx. Puede que esté protegido mediante contraseña. Para solucionar este problema, intente importar de nuevo el certificado o instale manualmente el certificado en el CSP de nombres seguros con el nombre de contenedor de clave siguiente: VS_KEY_F09E6382CB6E33D9	FacturacionElectronica.GeneradorXml

**Comment by giansalex** [comment]
Lo siento este proyecto no esta disponible para uso en produccion, para si quieres usarlo como muestra tienes que cargar certificado [FacturacionTIS.pfx](https://github.com/giansalex/facturacionTIS/blob/master/FacturacionElectronica.GeneradorXml/FacturacionTIS.pfx), la clave es `123456` en Propiedades de cada Proyecto que lo necesite.
![captura](https://user-images.githubusercontent.com/14926587/34622167-0f7ac268-f21a-11e7-9115-987359b4e600.PNG)

**Comment by abelnexus** [comment]
hola amigo :D , se que no hay soporte, pero eres el unico que me puede ayudar hasta ahora no logro crear el xml en C#, sigo analizando tu codigo, que clases debo usar para poder generar un xml usando como base este proyecto

**Comment by giansalex** [comment]
Hola, si has logrado compilar el proyecto, por el problema que tenias en la firma

**Comment by abelnexus** [comment]
si eso lo solucione, el detalle es que como son puras clases no se puede iniciar directamente y me pide que genere un ejecutable(y por eso entiendo un formulario) por eso te consulto amigo, estoy tratando de crear en base a un form y un button, y con tus clases crear el xml al darle clic. pero no se exactamente que clases debo usar

**Comment by giansalex** [comment]
Es que se maneja con proyectos de prueba, pero aqui hay un ejemplo
https://github.com/giansalex/facturacionTIS/blob/version_1/FacturacionElectronica.UI/frmTest.cs

**Comment by abelnexus** [comment]
es justo lo que queria hacer :D , muchas gracias esto me ayudara mucho mejor a entender te lo agradezco mucho

**Comment by abelnexus** [comment]
amigo disculpa la molestia,  no logro encontrar la ruta asignada para guardar el xml y cambiarlo:
(quiero sacarlo de archivos temporales y almacenar en otra carpeta)
           var objOperationResult = new OperationResult();
                var xmlResultPath = new XmlDocGenerator(_cert).GeneraDocumentoInvoice(ref objOperationResult, invoiceHeaderEntity);
                if (!objOperationResult.Success)
                {
                    MessageBox.Show(
                        objOperationResult.Error + '\n' + objOperationResult.InnerException + '\n' +
                        objOperationResult.Target, @"Error en el Process.", MessageBoxButtons.OK,
                        MessageBoxIcon.Error);
                    return;
                }

                if (string.IsNullOrEmpty(xmlResultPath)) return;
                if (!File.Exists(xmlResultPath)) return;
                //xmlResultPath = @"C:\Users\GRAFIKAS\Downloads\20600695771-01-F001-00000001.xml";
                Process.Start(xmlResultPath);
                var res = _ws.SendDocument(xmlResultPath);
                if (res.Success)
                {
                    if (res.ApplicationResponse == null) return;
                    
                    File.WriteAllBytes(Path.GetTempPath() + " / fileZip.zip", res.ContentZip);
                    Process.Start(Path.GetTempPath() + "/fileZip.zip");
                }

**Comment by giansalex** [comment]
la ruta que contiene `xmlResultPath` podrías moverlo a la carpeta que necesites

**Comment by abelnexus** [comment]
lo intente quitandole el //
xmlResultPath = @"C:\Users\GRAFIKAS\Downloads\xml\"; me abre la carpeta pero no crea el zip ni lo desevuelve y en temp sigue guardando el xml firmado

**Comment by abelnexus** [comment]
lo volvi a bajar y ahora no me corre :'v
me dice que no hay definicion para "CurrentService"

**Comment by giansalex** [comment]
eso estaba en la rama `version_1`, pero estoy haciendo varios cambios, asi que ahora mismo no podrias utilizar la version de master

**Comment by abelnexus** [comment]
hola amigo, no puedo solucionar este error me sale en master y en version_1
![captura](https://user-images.githubusercontent.com/34687414/48306436-85135000-e506-11e8-81cd-81de27ae4e76.PNG)

**Comment by abelnexus** [comment]
hola amigo :D 
ya encontre el error de currentservice, y ya estoy entendiendo mejor como funciona, mi duda es si se puede generar en la v2.1 veo que hay librerias que indican "2.1".

**Comment by giansalex** [comment]
Si, se puede generar en el UBL 2.1
